### ISSUE TITLE
能调试 c 语言吗,兄弟

### ISSUE THREAD

**Issue by wlz987** [xukanshan/the_truth_of_operationg_system#1]

**Comment by xukanshan** [comment]
能，今天录视频





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xukanshan/the_truth_of_operationg_system"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月6日(星期四) 下午5:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xukanshan/the_truth_of_operationg_system] 能调试 c 语言吗,兄弟 (Issue #1)
